apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-amazing-amazon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: not-amazing-amazon
  template:
    metadata:
      labels:
        app: not-amazing-amazon
    spec:
      containers:
        - name: not-amazing-amazon
          image: indigowar/not_amazing_amazon:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_HOST
              value: "postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgresql-cm
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: REDIS_DB
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: REDIS_PASSWORD
            - name: MINIO_HOST
              value: "minio"
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: not-amazing-amazon
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: not-amazing-amazon
  type: LoadBalancer
